# Generated by Django 5.2.4 on 2025-11-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('inputEmail', models.EmailField(max_length=254)),
                ('inputPhone', models.CharField(max_length=15)),
                ('inputPassword', models.CharField(max_length=10)),
                ('checkbox', models.BooleanField(default=False)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
